### ISSUE TITLE
태그 관리 관련 제안

### ISSUE THREAD

**Issue by kongchu2** [kongchu2/CocktailTagSearch#10]
현재 태그를 삭제하려면 포스트로 들어가 클릭하여 삭제하여야 합니다.
이러한 방식은 사용자에게 불편할 수 있다고 생각해
개인 마이페이지에서 태그를 삭제 할 수 있는 기능이 필요할 것 같습니다.

**Comment by Mmoka03** [comment]
좋은 의견이라고 생각합니다
또한, 똑같이 칵테일도 적용되는 이야기라고 생각합니다

마이페이지에서 선택 삭제라는 기능을 추가하여
삭제 버튼을 누른  후 좋아하는 태그 혹은 칵테일을 클릭한 다음
최종 확인을 하여 삭제하는 기능을 생각해 보았습니다.

더 좋은 방식으로 삭제하는 의견이 있으시다면 제안해 주십시오

**Comment by kongchu2** [comment]
선택 삭제 기능이 괜찮을 것 같습니다!

**Comment by kongchu2** [comment]
기능이 추가 되었습니다.
