### ISSUE TITLE
이미지 정리에 대하여

### ISSUE THREAD

**Issue by Mmoka03** [kongchu2/CocktailTagSearch#11]
현재 칵테일 만큼 이미지가 늘어나면서 image폴더가 매우 혼잡해 졌습니다.

image폴더 안에 폴더를 더 추가하여 분류할 필요가 있다고 생각합니다.

**Comment by kongchu2** [comment]
Cocktail과 Icon을 분리하여 관리하면 될 것 같습니다.

**Comment by kongchu2** [comment]
분리하였습니다.
