### ISSUE TITLE
개선사항

### ISSUE THREAD

**Issue by kongchu2** [kongchu2/CocktailTagSearch#12]
- [x] 쿼리 Limit
- [x] 필요한것만 SELECT하기 ( * -> 필요한것만 ex)cocktail_id, cocktail_name)

참고
이진파일 BLOB

**Comment by Mmoka03** [comment]
필요하다고 생각되는 부분에 해당 사항을 적용하였습니다.

변경사항을 확인해 주시고 테스트 후 더 필요한 부분이 있는지 말해주십시오.

**Comment by kongchu2** [comment]
좋읍니다
