### ISSUE TITLE
최적화 진척 확인 요청

### ISSUE THREAD

**Issue by Mmoka03** [kongchu2/CocktailTagSearch#13]
현재 최적화의 진척 정도를 확인하고 싶습니다.
저의 환경이 노트북인지라 다른 환경에서는 평균적으로 몇ms가 걸리는 지도 확인하고 싶습니다.
(저는 검색 기준으로 평균 TagSearch : 28ms, CocktailSearch : 32ms 입니다)

최적화 개선사항이 전부 진행되었다면 일정을 당기여 관리자 페이지 개발에 착수할 예정입니다.

관리자 페이지를 계정에 권한 부여 방식으로 만들 경우 토의가 필요하오니 확인해 주십시오.

**Comment by kongchu2** [comment]
TagSearch: 2.5ms, CocktailSearch:5ms

태그의 개수가 같지 않은 점에서 큰 차이가 날 것 같습니다만
일단은 이 정도입니다..

**Comment by kongchu2** [comment]
최적화가 충분히 이루어 진 것 같으니 관리자 페이지를 제작 하면 될 것 같습니다!

저희 서비스는 여러 사람들이 관리하는 서비스가 아니니 권한 부여보다는
관리자 계정을 따로 만들어 사용하는 것이 좋을 것 같습니다
또한 권한 부여 방식으로 만들 경우 많은 시간 소요가 예상이 됩니다

**Comment by Mmoka03** [comment]
동의합니다.

다만, 관리자 계정을 따로 만든다는 방식은 
코드에서 직접 해당 계정 멤버 아이디를 확인 후 관리자 페이지를 표시하는 방식인가요?
아니면 테이블의 구조를 변경하여 이건 관리자 계정이다 라고 표시하는 방식인가요?
또한, 테이블의 구조를 변경할 경우 어떻게 변경할 것인지 정할 필요가 있다고 봅니다.

저는 후자의 방식이 범용성이 높다고 생각합니다.
그리고 관리자다 관리자가 아니다로 나누어지니 boolean형으로 제작하는 것이 맞는 것 같습니다.
(오라클에서는 기본 boolean이 없어 char(1)으로 0/1 데이터를 넣어 사용합니다)

저와 동의견이시면 테이블 변경 코드 작성 후  코맨트에 올리겠습니다.

그리고 이후 개발은 같은 것을 개발하면 서로 꼬일 확률이 높기 때문에
둘 중 한명이 관리자 페이지를 개발하고 다른 한명이 선택 삭제 기능을 개발하게 분담하는 것이 좋을 것 같습니다.

확인해주시고 의견을 알려주세요.

**Comment by kongchu2** [comment]
저도 후자가 좋을 것 같습니다.

**Comment by Mmoka03** [comment]
ALTER TABLE MEMBER ADD PERMISSIONS CHAR(1) DEFAULT '0' NOT NULL; 
해당 코드로 컬럼을 추가해 주십시오.

역할 분담에 대해 따로 코맨트가 없으시면 제가 선택 삭제 기능을 맡겠습니다.

**Comment by kongchu2** [comment]
컬럼을 추가하였습니다.
그럼 제가 관리자 페이지를 맡는 것으로 하겠습니다.

**Comment by gojun89** [comment]
+ 최적화할 때에는 Cache 를 적용할 수도 있으니 시간나면 고민해 봐~

**Comment by kongchu2** [comment]
충분한 최적화가 이루어졌고
위에서 언급한 기능의 개발이 대부분 이루어졌습니다!
