### ISSUE TITLE
Member 테이블 password와 salt 컬럼의 범위 조정

### ISSUE THREAD

**Issue by Mmoka03** [kongchu2/CocktailTagSearch#16]
비밀번호를 암호화를 할 경우 변환할 경우
변환값이 예상보다 길어지는 현상이 일어났습니다.

이에 password와 salt 컬럼의 범위를 더욱 넓히기로 하였습니다.

변경된 쿼리문을 답글에 올리겠습니다.

ALTER TABLE MEMBER MODIFY(password VARCHAR2(64));
ALTER TABLE MEMBER MODIFY(password_salt VARCHAR2(32));

추가로 작업 영역이 겹칠 가능성이 높은 signup.jsp의 html변경 우선순위를 최대로 높혀주세요.

해당 작업이 끝난 것을 확인 후 기능을 적용하겠습니다.

**Comment by kongchu2** [comment]
signup.jsp의 html 변경 작업이 완료되었습니다.

**Comment by kongchu2** [comment]
작업이 완료되었습니다.
