### ISSUE TITLE
해상도에 따른 동적 불러오기?

### ISSUE THREAD

**Issue by kongchu2** [kongchu2/CocktailTagSearch#18]
![image](https://user-images.githubusercontent.com/48686444/111866958-47ffd800-89b4-11eb-947e-a2d09c2b238c.png)
저의 해상도 환경인 QHD(2560x1440)에서는 10개의 칵테일을 불러오는 것으로는 화면을 채우기에 부족했습니다.
그렇다고 단지 받아오는 칵테일의 개수를 늘리게 된다면 해상도가 작은 환경(ex 모바일) 에서는 쓸데없이 많은 데이터를 불러오는 것이 될 것입니다.
그렇기에 해상도에 따라서 불러오는 칵테일의 개수를 동적으로 정하는 편이 좋아 보입니다.

**Comment by gojun89** [comment]
더 해보는거야? ㅎ_ㅎ

**Comment by kongchu2** [comment]
넴 조금 더 해보려고요
완성했다고 생각할때까지 ㅎㅎ;;
