### ISSUE TITLE
첫 로드 시에 태그들과 칵테일에 대해~~

### ISSUE THREAD

**Issue by kongchu2** [kongchu2/CocktailTagSearch#6]
이후에 태그들과 칵테일의 수가 많아지게 된다면 한번에 불러오는데 무리가 생기게 될 것 같습니다.
지금 당장 해결해야 할 사안은 아니지만 나중에 시간이 남으면 칵테일 페이지네이션을 시도해 보는 것도 좋을 것 같습니다
태그도 한번에 다 불러오는 것 보다는 개수를 제한하거나 더 좋은 방법이 있을 것 같습니다!

**Comment by Mmoka03** [comment]
페이지를 나눈 것은 아니지만
최대로 표시되는 칵테일과 태그를 조정할 수 있도록 변수를 넣었습니다.

페이지네이션이라기엔 애매하지만 태그의 최대 표시 제한은 필요할 것 같아서 넣었습니다.

**Comment by kongchu2** [comment]
커밋 72f3235에서 limit 변수를 넣어 해결되었습니다.
