### ISSUE TITLE
함수명 변경과 파일명 변경에 대한 제안사항

### ISSUE THREAD

**Issue by Mmoka03** [kongchu2/CocktailTagSearch#7]
현재 몇가지 결정해야 하는 사항이 있습니다.

- 임시 함수명인 SearchTest의 함수명을 getCocktailItems로 변경을 고안 중입니다.
- Search, TagSearch 파일을 각각 TagSearch, CocktailSearch로 변경하여 가독성을 높히는 방안을 생각하고 있습니다.
- LoadCocktail과 LoadTag의 기능을 Search, TagSearch의 기능으로 대체할 수 있기에 해당 파일을 삭제하는 방안을 생각하고 있습니다.

의견이 있으시다면 말해주시고
없으시다면 제가 즉시 변경하도록 하겠습니다.

**Comment by kongchu2** [comment]
셋 다 괜찮은 것 같습니다 !!

**Comment by Mmoka03** [comment]
확인했습니다

해당 사항은 적용되었습니다.
