### ISSUE TITLE
[2021-02-19] 까지의 진행 상황

### ISSUE THREAD

**Issue by Mmoka03** [kongchu2/CocktailTagSearch#8]
모든 검색 기능, 태그 추가, 태그 삭제, 태그 설명 표시 등
핵심 기능이 눈에 띄는 버그없이 정상 구동이 됩니다.

다음 단계로 회원가입 기능을 만들 필요가 있습니다.

회원가입 기능 중에선 비밀번호 암호화가 계획되어 있었는데
작업 중 시간이 오래 걸린다면 포기할 예정입니다.

작업을 분담한다면 이렇게 됩니다.
- 회원가입 기능 제작
- 좋아하는 태그, 칵테일 구현을 위한 마이페이지 제작
- 기능을 수행하기 위한 디자인 제작

해당 기능을 제작할 때 코멘트를 달아주시길 바랍니다.

**Comment by kongchu2** [comment]
회원가입 기능은 signin.jsp로 이미 구현되어 있으나
페이지와 연결되어 있지 않은 상태입니다!

**Comment by kongchu2** [comment]
현재 포스트 페이지에서 좋아하는 칵테일에 추가하는 기능을 제작하고 있습니다.

**Comment by Mmoka03** [comment]
현재 마이페이지를 제작 중입니다

**Comment by kongchu2** [comment]
페이지에서 좋아하는 태그에 추가하는 기능을 제작하였습니다.

**Comment by Mmoka03** [comment]
기본적인 마이페이지를 제작하였습니다

**Comment by kongchu2** [comment]
기능 제작완료~~~
