### ISSUE TITLE
[2021-02-21] 까지의 진행 상황

### ISSUE THREAD

**Issue by Mmoka03** [kongchu2/CocktailTagSearch#9]
현재 계획 중인 메인 기능은 대부분 마무리가 되었습니다.

심각한 버그도 없고, 진행 속도도 순조롭기에 기능 개발 계획 범위를 넓혔습니다.

최우선적으로 개발해야 하는 기능은 아래와 같습니다.
- 메인 페이지에 좋아하는 태그 표시 창
- 메인 페이지의 좋아하는 태그 클릭 시 검색된 태그에 추가 기능
- 회원 정보 업데이트를 위한 페이지 및 기능
- 회원 탈퇴를 위한 기능
- 마이페이지에서 좋아하는 칵테일을 누를 시 해당 칵테일 페이지 이동

다음은 개발 우선순위가 낮은 기능입니다.
- 칵테일 및 태그를 관리하는 페이지
- 테마 설정
- 비밀번호 암호화

우선순위가 높은 기능을 우선적으로 처리하는 것을 목표로 합니다.

**Comment by Mmoka03** [comment]
사전에 계획한 대로 작업을 시작합니다.

[이태규]
- 메인 페이지에 좋아하는 태그 표시 창
- 메인 페이지의 좋아하는 태그 클릭 시 검색된 태그에 추가 기능
- 마이페이지에서 좋아하는 칵테일을 누를 시 해당 칵테일 페이지 이동

[홍준혁]
- 회원 정보 업데이트를 위한 페이지 및 기능
- 회원 탈퇴를 위한 기능

먼저 작업이 마무리가 된다면 보고 후 우선순위가 낮은 작업에 들어갑니다
다만, 다른 쪽에서 도움이 필요할 경우 도우러 갑니다.

**Comment by Mmoka03** [comment]
담당한 기능 제작이 끝났습니다.

다음은 칵테일 및 태그를 관리하는 페이지 및 기능을 제작하도록 하겠습니다.

**Comment by kongchu2** [comment]
위에 작성한 기능의 제작이 완료되었습니다.
